sudo: required

language: python

python:
  - 3.4

services:
  - docker
  
script:
  - docker build -t joe/simply_fit .
  - docker run --name=simply_fit --detach=true --restart=always --publish=8001:8000 joe/simply_fit:latest
  - docker exec simply_fit python manage.py test simply_fit_api
